### ISSUE TITLE
Consecutive uppercase letters

### ISSUE THREAD

**Issue by lassik** [akicho8/string-inflection#22]
Is this intentional?

    (string-inflection-underscore-function "ASingleLine")

returns `"asingle_line"`. I would have expected it to return `"a_single_line"`.

Is this because of acronyms like `PHP`? So in this example, it could assume `AS` to be an acronym without human knowledge of the context.

Would it be a ridiculous idea to have a dictionary of common acronyms to cover cases like this?

**Comment by lassik** [comment]
Actually, it might be enough if it took one uppercase letter followed by one or more lowercase letters (e.g. `Dada`) to mean "this is a word, keep this as one word in the result". So:

    ASingleLine   ->   a_single_line
    PHPMode       ->   php_mode
    EndsWithPHP   ->   ends_with_php

**Comment by akicho8** [comment]
Thank you for raising a problem

I noticed that `ASingleLine` would be` asingle_line`.
Because it is not so much, I did not think it was a problem in particular.
However, it is certainly better for `ASingleLine` to be` a_single_line`.

And I think it's hard to have a dictionary of abbreviations such as `PHP`.
I am not very motivated.

**Comment by akicho8** [comment]
It became very convenient.
It is a wonderful contribution.
Thank you! 😄

**Comment by lassik** [comment]
Yeah, we got lucky, it seems that a one-line fix solved the entire problem :) Thanks for the quick response, makes it fun to contribute!
