### ISSUE TITLE
`string-inflection-get-current-word` is not mode aware

### ISSUE THREAD

**Issue by johannes-mueller** [akicho8/string-inflection#40]
When editing a python file like
```
fooBar-barFoo
         ^---- cursor position
```

and calling `string-inflection-python-style-cycle` the result is
```
foo_bar_bar_foo
```

and not the expected
```
fooBar-bar_foo
```

Probably the mode aware `(symbol-at-point)` function should be used to determine the current word.

**Comment by akicho8** [comment]
Thank you very much for making various improvements.

The reasons I treated words connected by hyphens (kebab-case) as a single word for conversion were:

1. Personally, it was convenient to convert them regardless of the current mode.
1. I wasn't fully aware of the technical method to switch word boundaries depending on the mode.

In the example you provided, it is indeed true that, in most cases, when in python-mode, the hyphen in fooBar-barFoo would likely represent a minus operator. Therefore, many people might find it more convenient to treat barFoo as a separate word (variable name) rather than considering the whole thing as one word.

I also believe that, as an Emacs convention, it is more natural to switch depending on the mode.

**Comment by akicho8** [comment]
Thank you for the pull request.

I set string-inflection-final-position to 'remain and have been using it for a bit.
However, I noticed an issue when editing a Ruby file. For example:

```
FOO_BAR
       ^---- cursor position
```

After calling string-inflection-ruby-style-cycle, the result is:

```
FooBar

^---- cursor position
```

The cursor ends up here, which interrupts continuous transformations.

The correct behavior should be:

```
FooBar
      ^---- cursor position
```

or

```
FooBar
     ^---- cursor position
```

This is the only part that concerns me.
